name: FAST-B_1_4_finetune_40e
warmup_epochs: 2.5
ema: true
save_model: true
batch_size: 16
num_workers: 12
# split_seed: 42

wandb:
    project_name: VQA_Experiments_2022

data:
    train:
        type: FusionDataset
        args:
            phase: train
            anno_file: ./examplar_data_labels/VDPVE/train_labels.txt
            data_prefix: ../data/train
            sample_types:
                fragments:
                    fragments_h: 7
                    fragments_w: 7
                    fsize_h: 32
                    fsize_w: 32
                    aligned: 32
                    clip_len: 32
                    frame_interval: 2
                    num_clips: 1

# Evalue settings loaded by split_train.py
    val-vqpve:
        type: FusionDataset
        args:
            phase: test
            # subset1: offline val
            anno_file: ./examplar_data_labels/VDPVE/val_offline_labels.txt
            data_prefix: ../data/train

            sample_types:
                fragments:
                    fragments_h: 7    # 1, 7
                    fragments_w: 7    # 1, 7
                    fsize_h: 32    # 224, 32
                    fsize_w: 32    # 224, 32
                    aligned: 32
                    clip_len: 32
                    frame_interval: 2
                    num_clips: 4


model:
    type: DiViDeAddEvaluator
    args:
        backbone:
            fragments:
                # checkpoint: false
                # pretrained: 
        backbone_size: swin_tiny_grpb
        backbone_preserve_keys: fragments
        divide_head: false
        vqa_head:
            in_channels: 768
            hidden_channels: 64
            dropout_ratio: 0.5
            
optimizer:
    lr: !!float 1e-3
    backbone_lr_mult: !!float 1e-1
    wd: 0.01
        
load_path: ./pretrained_weights/FAST_VQA_B_1_4.pth
# load_path: ./pretrained_weights/swin_tiny_patch244_window877_kinetics400_1k.pth
test_load_path: 

    
        
